package com.launchwindow.model;

public enum NotificationType {
    FRIEND_REQUEST_RECEIVED,
    FRIEND_REQUEST_ACCEPTED,
    FRIEND_REQUEST_DECLINED,
    CALENDAR_INVITATION_RECEIVED,
    CALENDAR_INVITATION_ACCEPTED,
    CALENDAR_INVITATION_DECLINED
}